City:
  type: entity
  table: cities
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    city_name:
      type: string
    timezone:
      type: string
    country_code:
      type: string
  oneToOne:
    data:
      targetEntity: Data
      mappedBy: city