version: '2'
services:
  web:
    build: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./../:/var/www
    tty: true

  php:
    build: ./php-fpm
    volumes:
        - ./../:/var/www:cached
        - ./../logs:/var/www/var/logs:cached
    links:
        - db
    ports:
      - '9001:9000'

  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password", "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"]
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 81:80
    depends_on:
      - db
    environment:
      MYSQL_USERNAME: symfony
      MYSQL_ROOT_PASSWORD: symfony
      PMA_HOSTS: db